name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Optional: Add steps to build your site here
      # For example, if you're using a static site generator.

      - name: Setup Pages
        uses: actions/configure-pages@v4

      # This step ensures that only index.html and any other necessary files are deployed.
      - name: Prepare deployment
        run: |
          mkdir public
          cp sidt-website/templates/index.html public/
          # Add any other necessary files to the public directory here

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'  # Specify the directory containing index.html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
